defaults:
  - _self_
  - experiment: exp1

# Base settings used by src/sign_ml/train.py
device: auto

optimizer:
  _target_: torch.optim.Adam

paths:
  model_out: models/traffic_sign_model.pt

hydra:
  run:
    dir: ${oc.env:PROJECT_ROOT}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true
